
pipeline {
    agent {label "${params.MACHINE_LABEL}"}
    parameters {
        string (defaultValue: '', description: 'Machine label expression for jenkins node, like Linux&&390 or aix&&ppc, etc', name: 'MACHINE_LABEL')
        choice (choices: 'linux_x86-64\nosx_x86-64\nlinux_ppc-64\nlinux_ppc-64_le_gcc\nlinux_armmak\nlinux_390-64\naix_ppc-64', description: 'SPEC?', name: 'SPEC')
    }
    environment {
        PATH = "/usr/lib/ccache/:$PATH"
        GEN_GTEST_OUTPUT = true
    }
    stages {

        stage('Build') {
            steps {
                timestamps {
                    echo 'Configure...'
                    sh '''pwd'''
                    // sh'''cd omr'''
                    sh'''make -f run_configure.mk OMRGLUE=./example/glue SPEC=linux_x86-64'''
                   
                    echo 'Compile...'
                    sh '''make -j8'''

                }
            }
        }
        stage('Test') {
            steps {
                timestamps {
                    echo "Sanity Test..."
                    sh '''make test'''
                    sh '''ls'''
                }
            }
        }
    }
    post {
        unstable {
            archiveArtifacts artifacts: '**/test_output/**', fingerprint: true, allowEmptyArchive: true
        }
        always {
            step([$class: 'XUnitBuilder',
                thresholds: [[$class: 'FailedThreshold', unstableThreshold: '1']],
                tools: [[$class: 'GoogleTestType', skipNoTestFiles: true, pattern: '**/test_output/**']]])

            echo 'Cleanup workspace'
            deleteDir()
        }
    }
}